# Generated by Django 5.0.6 on 2024-05-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_vacancies_vacancy_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCVs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog', to='mainsite.blogcategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
