# Generated by Django 5.0.6 on 2024-06-05 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_usercvs_alter_blog_post_cat_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercvs',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterField(
            model_name='usercvs',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usercvs',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'zip', 'rar'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='usercvs',
            name='phone',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Введите действительный номер', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Телефон'),
        ),
    ]
